/*
#include <iostream> // Exceptions @ http://www.cplusplus.com/doc/tutorial/exceptions/
using namespace std;

int main () {
	try {
		//throw 20;
		//throw 'a';
		throw "abc";
	}
	catch (int param) { cout << "int exception" << endl; }
	catch (char param) { cout << "char exception" << endl; }
	catch (...) { cout << "default exception" << endl; }

	return 0;
}
*/
